site_name: Syntinel
pages:
- Home: index.md
- Core:
  - Requests:
    - Signal Request: classes/requests/signal-request.md
    - Status Request: classes/requests/status-request.md
  - Database Records:
    - Channel DB Record: classes/database/channel-db.md
    - Reporter DB Record: classes/database/reporter-db.md
    - Router DB Record: classes/database/router-db.md
    - Signal DB Record: classes/database/signal-db.md
    - Template DB Record: classes/database/template-db.md
  - Channels:
    - Slack: core/channels/slack.md
    - Microsoft Teams: core/channels/teams.md
  - Actions:
    - Button: core/actions/button.md
    - Choice: core/actions/choice.md
  - Templates: core/templates.md
  - Router: core/router.md
- Resolvers:
  - Overview: resolvers/overview.md
  - Echo Resolver: resolvers/echo.md
  - AWSLambda Resolver: resolvers/aws-lambda.md
- Implementations:
  - Amazon Web Services (AWS): implementations/amazon-web-services.md

theme: mkdocs