site_name: Syntinel
pages:
- Syntinel: index.md
- Core Inputs:
  - Signal: classes/signal-request.md
  - Status: classes/status-request.md
- Database Objects: 
  - Classes: classes/database.md
  - DynamoDb: databases/dynamodb.md
- Resolvers:
  - Overview: resolvers.md
  - Echo Resolver: resolvers/echo.md
  - AWSLambda Resolver: resolvers/aws-lambda.md
- Implementations:
  - Amazon Web Services (AWS): implementations/aws.md

theme: readthedocs