site_name: Synapse
pages:
- Synapse: index.md
- Architecture: architecture.md
- Quick Start: quickstart.md
- Plans:
  - Overview: plans.md
  - Actions: plans/actions/index.md
  - Parameters: plans/parms/index.md
  - Handlers: plans/handlers.md
  - RunAs: plans/runas.md
  - Examples:
    - Complete YAML: yaml.md
- Usage:
  - Installation/Configuration:
    - Controller/Node: run/setup.md
    - Data Access Layer: run/dal.md
    - Setup:
      - Options: run/setup/options.md
      - Authentication: run/setup/authentication.md
      - Impersonation: run/setup/impersonation.md
      - Authorization: run/setup/authorization.md
      - RBAC: run/setup/rbac.md
    - SSL/TLS: run/ssl.md
    - Encrypting Plans: run/crypto.md
  - Web API:
    - Controller: run/controller.md
    - Postman Example: run/postman.md
    - Node: run/node.md
    - Admin: run/admin.md
    - Swagger: run/swagger.md
    - AutoUpdate: run/autoupdate.md
  - CommandLines:
    - Core: cli/core.md
    - Controller: cli/controller.md
    - Node: cli/node.md
    - Server: cli/server.md
  - SDK:
    - About: sdk/index.md
    - Custom Handlers: sdk/handlers.md
    - Custom Controller:
      - Overview: sdk/controller/index.md
      - Auto-Generate: sdk/controller/util.md
      - Code in VS: sdk/controller/vs.md
- Handlers:
  - About: handlers/about.md
  - CommandLine:
    - Command Handler: handlers/commandline/command.md
    - Script Handler: handlers/commandline/script.md
  - Database:
    - SqlServer: handlers/sql/sqlserver.md
    - Oracle: handlers/sql/oracle.md
    - Odbc: handlers/sql/odbc.md
  - Active Directory:
    - Handler: handlers/ad/handler.md
    - Api: handlers/ad/api.md
    - Role Managers: handlers/ad/rolemanager.md
  - DNS:
    - DNS Handler: handlers/dns/index.md
  - Cloud:
    - AWS Handler: handlers/cloud/aws.md
  - FileUtil:
    - CopyFile Handler: handlers/fileutil/copyfile.md
    - DeleteFile Handler: handlers/fileutil/deletefile.md
    - MungeFile Handler: handlers/fileutil/mungefile.md
  - Data Transformation:
    - Transform Handler: handlers/datatransformation/index.md
  - URI:
    - REST Handler: handlers/uri/rest.md
- UI:
  - How To Use: ui/howtouse.md
  - How To Contribute: ui/howtocontribute.md
- Releases: releases.md
- Roadmap: roadmap.md
- Support: support.md
- Examples:
  - Parameters:
    - YAML:
      - Basic: plans/parms/yaml/basic.md
      - ForEach: plans/parms/yaml/foreach.md
    - JSON:
      - Basic: plans/parms/json/basic.md
      - ForEach: plans/parms/json/foreach.md
    - XML:
      - Basic: plans/parms/xml/basic.md
      - ForEach: plans/parms/xml/foreach.md
  - Complete YAML: yaml.md
theme: readthedocs