site_name: Syntinel
pages:
- Syntinel: index.md
- Core Inputs:
  - Signal: classes/signal-request.md
  - Status: classes/status-request.md
- Resolvers: resolvers.md
  - Echo: resolvers/echo.md
  - AWSLambda: resolvers/aws-lambda.md

theme: readthedocs