site_name: Syntinel
pages:
- Syntinel: index.md
- Core Inputs:
  - Signal: classes/signal-request.md
  - Status: classes/status-request.md
- Resolvers:
  - Overview: resolvers.md
  - Echo Resolver: resolvers/echo.md
  - AWSLambda Resolver: resolvers/aws-lambda.md

theme: readthedocs